__target__: cell_observatory_finetune.models.heads.linear_head.LinearHead

in_dim: 256
input_format: ${dataset_layout_order}
input_shape: ${eval:"[${clusters.batch_size_per_gpu}] + ${datasets.input_shape}"}

use_bn: False
nlayers: 3
hidden_dim: 2048
mlp_bias: True