defaults:
  - _self_

_target_: finetune.data.databases.database.SQLiteDatabase

db_path: /clusterfs/nvme/segment_4d/testing/db_test.sqlite
db_readpath: /clusterfs/nvme/segment_4d/testing/db_tables
db_savepath: /clusterfs/nvme/segment_4d/testing/db_tables

db_read_method: "feather"
db_save_method: "feather"
force_create_db: false

# FIXME: here TCZYX but elsewhere TZYXC
data_tile: [1, 5, 32, 32, 32]
label_tile: [32, 32, 32]

label_spec:
  _target_: finetune.data.databases.schema.DB_LabelSchema
  table: "instance_segmentations"
  label_metadata:
    label_id: null
    img_id: null
    t0: null
    t1: null
    z: null
    y: null
    x: null
    experiment_id: null   
    fish_id: null
    roi_id: null
    tile_id: null
    label_path: null    
    instance_ids: null       
    bboxes: null  
    dtype: null

data_specs:
  # to allow for multiple schemas for different tables/datasets 
  - _target_: finetune.data.databases.schema.DB_DataSchema
    table: "synthetic_skittlez"
    data_attributes:
      img_id: null
      img_path: null
      shape: null
      dtype: null
      t: null
      c: null
      z: null
      y: null
      x: null
    quality_metrics: null
    sample_metadata:
      img_id: null 
      marker_targets: null  
      tissues: null
    reagents_metadata: null
    accquisition_metadata:
      img_id: null
      experiment_id: null 
      fish_id: null
      roi_id: null
      tile_id: null