defaults:
  - metrics: metrics
  - _self_  # self reference last to allow for overrides

val_begin: 0
val_interval: 1

# TODO: coordinate with ray config in checkpoint.yaml
val_metric: ap@50 # needs to be one of the metrics defined in metrics.yaml
val_mode: max # mode for the validation metric, can be 'max' or 'min'

evaluator:
  _target_: finetune.evaluation.skittlez_evaluation.SkittlezInstanceEvaluator
  metrics: ${evaluation.metrics}  # metrics to use for evaluation