defaults:
  - _self_
  - /models: maskrcnn        # Loads configs/models/mask_rcnn.yaml
  - /models/backbones: resnet     # Loads configs/models/backbones/resnet.yaml
  - /datasets: skittlez_eval       # Loads configs/datasets/skittlez.yaml
  - /metrics: metrics_skittlez_eval        # Loads configs/metrics/metrics_skittlez_eval.yaml
  - /transforms: transforms_skittlez_eval # Loads configs/transforms/transforms_skittlez_eval.yaml

# Skittlez eval parameters
backbone_out_channels: 512 # C5 = 2048
backbone_target: segmentation.models.backbones.resnet.resnet50

eval_type: skittlez_eval
results_dir: /clusterfs/nvme/segment_4d/test_5/evaluation
train_db_savedir: /clusterfs/nvme/segment_4d/test_5/db

checkpointdir: /clusterfs/nvme/segment_4d/test_5/checkpoints
ckpt_suffix: "best" # generally, "last" or "best"

# evaluator parameters
warmup_iters: 1

# Compute resources
workers: 1 # number of worker nodes
gpu_workers: 1 #4 # number of gpus per worker
cpu_workers: 4 #16 # number of cpu cores per worker (num gpus per worker * number of cpu cores per gpu)
distributed_sampler: false

# Quantization
amp: fp16  # ["no", "fp16", "bf16", "fp8"]

# DeepSpeed config for checkpoint loading
deepspeed_config:
  zero_optimization:
    stage: null # run eval on 1 gpu, no need for zero optimization 