_target_: cell_observatory_finetune.models.meta_arch.jepa.FinetuneJEPA
input_fmt: ${dataset_layout_order}
input_shape: ${eval:"[${clusters.batch_size_per_gpu}] + ${datasets.input_shape}"}
temporal_patch_size: ${datasets.patch_shape.0}
lateral_patch_size: ${datasets.patch_shape.1}
axial_patch_size: ${datasets.patch_shape.2}

embed_dim: 1664
predictor_embed_dim: 1024
depth: 48
predictor_depth: 16
num_heads: 16
predictor_num_heads: 16
mlp_ratio: 4.9230769231

proj_drop_rate: 0.0
att_drop_rate: 0.0
drop_path_rate: 0.1
init_std: 0.02
fixed_dropout_depth: false
use_conv_proj: false
norm_layer: RmsNorm
act_layer: SiLU
mlp_layer: SwiGLU

mask_ratio: 0.75
window_mask_shape: null

abs_sincos_enc: true
rope_pos_enc: false
rope_random_rotation_per_head: true
rope_mixed: false
rope_theta: 100.0
weight_init_type: vjepa2
mlp_wide_silu: false
loss_fn: l1_masked