defaults:
  - _self_

_target_: segmentation.platform.models.patch_embeddings.PatchEmbedding

input_fmt: ${datasets.input_format}
input_shape:
  - 1    # B
  - 1    # T
  - 128  # Z
  - 128  # Y
  - 128  # X 
  - 2
lateral_patch_size: ${models.backbones.lateral_patch_size}
axial_patch_size: ${models.backbones.axial_patch_size}
temporal_patch_size: ${models.backbones.temporal_patch_size}
# TODO: masked encoder currently does not support temporal patch size
# temporal_patch_size: ${models.backbones.masked_encoder_wrapper.temporal_patch_size}
embed_dim: ${models.backbones.embed_dim}
channels: 2