defaults:
  - _self_

_target_: segmentation.evaluation.skittlez_evaluation.SkittlezInstanceEvaluator

metrics:
  ap@50:
    _target_: segmentation.metrics.metrics.AveragePrecision
    iou_threshold: 0.5
  ap@75:
    _target_: segmentation.metrics.metrics.AveragePrecision
    iou_threshold: 0.75
  ap@90:
    _target_: segmentation.metrics.metrics.AveragePrecision
    iou_threshold: 0.9