defaults:
  - _self_

_target_: segmentation.metrics.metrics.MetricCompose

metrics:
  ap@50:
    _target_: segmentation.metrics.metrics.AveragePrecision
    iou_threshold: 0.5
    detection_mode: true
  ap@75:
    _target_: segmentation.metrics.metrics.AveragePrecision
    iou_threshold: 0.75
    detection_mode: true
  ap@90:
    _target_: segmentation.metrics.metrics.AveragePrecision
    iou_threshold: 0.9
    detection_mode: true