_target_: cell_observatory_finetune.models.meta_arch.maskdino.MaskDINO
  
criterion: 
  ${losses}

num_queries: 100
size_divisibility: 32

topk_per_image: 100
focus_on_boxes: False
use_softmax_loss: False
instance_segmentation_flag: True