defaults:
  - _self_

transforms_list:
  - _target_: finetune.data.transforms.transforms.Normalize
    # mean: ${dataset_mean}
    # std: ${dataset_std}
  - _target_: finetune.data.transforms.transforms.Resize
    size: 
      - 256
      - 256
      - 256