_target_: cell_observatory_finetune.data.masking.mask_generator.MaskGenerator

data_layout: ${datasets.input_format}
input_shape: ${datasets.input_shape}
patch_shape: ${datasets.patch_shape}
lateral_mask_scale: 0.5
axial_mask_scale: 0.5
temporal_mask_scale: 0.2
aspect_ratio_scale_hw: 0.2
aspect_ratio_scale_hd: 0.2
random_masking_ratio: 0.5
channels_to_mask: [0]
time_downsample_pattern: [0,1,0,1]
mask_mode: blocked