defaults:
  - _self_

# TODO: we refrain from placing the mask_generator as a collate funciton 
#       for performance reasons
# collate_fn:
#   _target_: data.masking.mask_generator.MaskCollator
#   base_collator: data.datasets.pretrain_dataset.collate_pretrain_dataset

mask_generators:
  - _target_: data.masking.mask_generator.MaskGenerator
    layout: ${datasets.dataset.input_layout}
    input_shape: ${datasets.input_shape}
    temporal_patch_size: ${datasets.patch_shape.0}
    axial_patch_size: ${datasets.patch_shape.1}
    lateral_patch_size: ${datasets.patch_shape.2}

    lateral_mask_scale: 0.5
    axial_mask_scale: 0.5
    temporal_mask_scale: 0.5

    aspect_ratio_scale_hw: 0.5
    random_masking_ratio: 0.75
    num_blocks: 2

    channels_to_mask: null
    time_downsample_pattern: null
    mask_mode: 
      _target_: data.masking.mask_generator.MaskModes
      value: "random"