defaults:
  - _self_

mask_generators:
  - _target_: data.masking.mask_generator.MaskGenerator
    layout: ${datasets.dataset.input_layout}
    input_shape: ${datasets.input_shape}
    patch_shape: ${datasets.patch_shape}

    lateral_mask_scale: 0.5
    axial_mask_scale: 0.5
    temporal_mask_scale: 0.5

    aspect_ratio_scale_hw: 0.5
    random_masking_ratio: 0.75
    num_blocks: 2

    channels_to_mask: null
    time_downsample_pattern: [1, 0, 0, 0, 0, 0, 0, 0]
    mask_mode: 
      _target_: data.masking.mask_generator.MaskModes
      value: "blocked_patterned"