defaults:
  - _self_

ap@50:
  _target_: finetune.evaluation.metrics.metrics.AveragePrecision
  iou_threshold: 0.5
ap@75:
  _target_: finetune.evaluation.metrics.metrics.AveragePrecision
  iou_threshold: 0.75
ap@90:
  _target_: finetune.evaluation.metrics.metrics.AveragePrecision
  iou_threshold: 0.9