_target_: cell_observatory_finetune.models.layers.losses.DETR_Set_Loss

losses: ["labels", "masks", "boxes"]
denoise_losses: ["labels", "masks", "boxes"]

matcher:
  ${models.matchers}

num_classes: ${datasets.num_classes}

loss_weight_dict:
  loss_ce: ${models.matchers.cost_classification}
  loss_mask: ${models.matchers.cost_mask}
  loss_dice: ${models.matchers.cost_mask_dice}
  loss_giou: ${models.matchers.cost_box_giou}
  loss_bbox: ${models.matchers.cost_box}
  loss_ce_interm: ${models.matchers.cost_classification}
  loss_mask_interm: ${models.matchers.cost_mask}
  loss_dice_interm: ${models.matchers.cost_mask_dice}
  loss_giou_interm: ${models.matchers.cost_box_giou}
  loss_bbox_interm: ${models.matchers.cost_box}
  loss_ce_dn: ${models.matchers.cost_classification}
  loss_mask_dn: ${models.matchers.cost_mask}
  loss_dice_dn: ${models.matchers.cost_mask_dice}
  loss_giou_dn: ${models.matchers.cost_box_giou}
  loss_bbox_dn: ${models.matchers.cost_box}

no_object_loss_weight: 0.1

num_points: 12544 # 112x112
oversample_ratio: 3.0    
importance_sample_ratio: 0.75 

denoise: True
denoise_type: "seg"

semantic_ce_loss: False
focal_alpha: 0.25