defaults:
  - _self_

_target_: segmentation.data.databases.supabase_database.SupabaseDatabase

# inherit task from dataset name
train_task: ${..name}

dotenv_path: /clusterfs/nvme/hph/git_managed/env/credentials.env

db_readpath: /clusterfs/nvme/segment_4d/testing2/db_tables_test8
db_savepath: /clusterfs/nvme/segment_4d/testing2/db_tables_test8

db_read_method: "feather"
db_save_method: "feather"
force_create_db: false

# FIXME: here TCZYX but elsewhere TZYXC
data_tile: [1, 2, 128, 128, 128]
label_tile: [1, 128, 128, 128]

tile: true
with_labels: false

# NOTE: the base specs should purposefully be kept 
# minimal to allow for easy overrides in other configs
# since dataclass classes are more tricky to override
# in Hydra configs

label_spec:
  _target_: segmentation.data.databases.schema.DB_LabelSchema
  table: "instance_segmentations"
  label_metadata:
    # label_id: null
    id: null
    server_folder: null
    output_folder: null
    # time_size: null
    z_start: null
    z_end: null
    y_start: null
    y_end: null
    x_start: null
    x_end: null
    # experiment_id: null   
    # fish_id: null
    # roi_id: null
    # tile_id: null
    # label_path: null    
    # instance_ids: null       
    # bboxes: null  
    # dtype: null

data_specs:
  # to allow for multiple schemas for different tables/datasets 
  - _target_: segmentation.data.databases.schema.DB_DataSchema
    table: "prepared"
    data_attributes:
      id: null
      server_folder: null
      output_folder: null
      # img_path: null
      # shape: null
      # dtype: null
      # time_size: null
      # channel_size: null
      z_start: null
      z_end: null
      y_start: null
      y_end: null
      x_start: null
      x_end: null
    # quality_metrics: null
    # sample_metadata:
    #   id: null
    #   marker_targets: null  
    #   tissues: null
    # reagents_metadata: null
    # accquisition_metadata:
    #   id: null
    #   experiment_id: null 
    #   fish_id: null
    #   roi_id: null
    #   tile_id: null