type: cosine
epochs: 5
warmup: 1
cooldown: 1
fixedlr: false
ema: [0.998, 1.0]
warmup_min_ratio: 0.5
cos_min_ratio: 0.0001
warmup_type: linear
update_type: epoch

wd_scheduler:
  enabled: true
  final_wd: 0.0
  ref_wd: ${optimizers.wd}