type: warmup_stable_decay
epochs: 500
warmup: 10
cooldown: 50
fixedlr: false
ema: [0.998, 1.0]
warmup_min_ratio: 0.5
final_lr_ratio: 0.0001
warmup_type: linear
update_type: step

wd_scheduler:
  enabled: true
  final_wd: 0.0
  ref_wd: ${optimizers.wd}