defaults:
  # important to set _self_ first since mask_generator
  # depends on the initialization of the input_format
  - databases: supabase_database        # Loads configs/datasets/databases/supabase_database.yaml
  - _self_
  - masking: mask_generator # Loads configs/datasets/masking/mask_generator.yaml

# dataset Parameters (mainly used by other configs)
name: channel_split

split:  0.0
channel_in: 1
num_classes: 2   
input_format: 
  _target_: cell_observatory_finetune.data.structures.data_objects.data_shapes.MULTICHANNEL_4D_HYPERCUBE
  value: TZYXC

input_shape: 
  - 1
  - 128
  - 128
  - 128
  - 1
patch_shape: 
  - ${models.backbones.temporal_patch_size} # T
  - ${models.backbones.lateral_patch_size} # Z
  - ${models.backbones.axial_patch_size} # Y
  - ${models.backbones.axial_patch_size} # X
  - 1 # C

dataloader_type: torch
return_dataloader: true
distributed_sampler: true
collate_fn: cell_observatory_finetune.data.utils.collate_channel_split

# TODO: remove, not used anymore
worker_init_fn: cell_observatory_finetune.data.utils.worker_init_fn 
dataset_mean: [0,0,0,0,0]  
dataset_std: [1,1,1,1,1]  

dataset:
  _target_: cell_observatory_finetune.data.datasets.channel_split_dataset.ChannelSplitDataset 
  db: null
  transforms: null
  input_format: 
    _target_: cell_observatory_finetune.data.structures.data_objects.data_shapes.MULTICHANNEL_4D_HYPERCUBE
    value: TZYXC
  # not used for channel_split
  key_cols:
    - id
    - t0
    - t1
    - z0
    - y0
    - x0