defaults:
  - databases: sqlite_database        # Loads configs/datasets/databases/sqlite_database.yaml
  - _self_

# Dataset Parameters (mainly used by other configs)
name: instance_segmentation

split:  0.1
channel_in: 5
num_classes: 2   
input_shape: 
  - 256
  - 256
  - 256
dataloader_type: torch
return_dataloader: true
distributed_sampler: true
collate_fn: cell_observatory_finetune.data.utils.collate_instance_segmentation
# TODO: remove, not used anymore
worker_init_fn: cell_observatory_finetune.data.utils.worker_init_fn 

# not used
dataset_mean: [0,0,0,0,0]  
dataset_std: [1,1,1,1,1]  

dataset:
  _target_: cell_observatory_finetune.data.datasets.instance_seg_dataset.InstanceSegDataset 
  layout: "ZYXC"
  key_cols:
    - img_id
    - t0
    - t1
    - z0
    - y0
    - x0